---
- 
  name: Container testing
  hosts: all

  tasks:
    - 
      name: Container creation test
      command: "docker container run -itd --name=test -p 83:80 yogeshraheja/devopsinaction:v1"

    -
      name: List containers
      command: "docker container ls -a"
      register: containerlist

    - 
      name: Checking outputs
      debug: var=containerlist
